server:
  port: 9030
spring:
  application:
    name: coa-server
eureka:
  client:
    service-url:
      defaultZone: http://10.21.17.175:18081/eureka/,http://10.21.17.175:18082/eureka/,http://10.21.17.175:18083/eureka/